import{a as S,S as v,i}from"./assets/vendor-5YrzWRhu.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))h(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&h(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function h(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const q="51915317-a5ee9a5ba63d3f1e31a6123a4",R="https://pixabay.com/api/";async function m(r,e=1){try{return(await S.get(R,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}})).data}catch(o){return console.error("Помилка запиту до Pixabay API:",o),null}}const y=document.querySelector(".gallery"),g=document.querySelector(".loader"),b=document.querySelector(".load-more");let u;function L(r){const e=r.map(o=>`
      <li class="photo-card">
        <a href="${o.largeImageURL}">
          <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${o.likes}</p>
          <p><b>Views:</b> ${o.views}</p>
          <p><b>Comments:</b> ${o.comments}</p>
          <p><b>Downloads:</b> ${o.downloads}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",e),u?u.refresh():u=new v(".gallery a",{captionsData:"alt",captionDelay:250})}function M(){y.innerHTML=""}function w(){g.hidden=!1}function p(){g.hidden=!0}function f(){b.hidden=!1}function c(){b.hidden=!0}const P=document.querySelector("#search-form"),$=document.querySelector(".load-more");let s="",a=1,l=0;p();c();P.addEventListener("submit",B);$.addEventListener("click",O);async function B(r){if(r.preventDefault(),s=r.currentTarget.searchQuery.value.trim(),!s){i.warning({title:"Увага",message:"Введіть пошуковий запит!",position:"topRight"});return}a=1,l=0,M(),c(),r.currentTarget.searchQuery.value="";try{w();const e=await m(s,a);if(!e||e.hits.length===0){i.info({title:"Немає результатів",message:"За вашим запитом нічого не знайдено.",position:"topRight"});return}l=e.totalHits,L(e.hits),l>15?f():i.info({title:"Кінець",message:"Більше зображень немає.",position:"topRight"})}catch{i.error({title:"Помилка",message:"Не вдалося завантажити зображення. Спробуйте пізніше.",position:"topRight"})}finally{p()}}async function O(){a+=1,c(),w();try{const r=await m(s,a);if(L(r.hits),document.querySelector(".gallery li")){const{height:o}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const e=Math.ceil(l/15);a>=e?(i.info({title:"Кінець",message:"Більше зображень немає.",position:"topRight"}),c()):f()}catch{i.error({title:"Помилка",message:"Не вдалося завантажити більше зображень.",position:"topRight"}),f()}finally{p()}}
//# sourceMappingURL=index.js.map
